title: ViewChild in Angular2
description: This blog discusses parent and child component interaction using ViewChild.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
